#!/usr/bin/env python3
"""Implementation for agent-skills-builder (v0.10.0).

Harness-optimized with 5-phase verification loops, domain-specific eval criteria,
model routing, sub-agent orchestration, and error recovery protocol.
"""

from __future__ import annotations

import json
import re
from pathlib import Path
from zipfile import ZIP_DEFLATED, ZipFile


SKILL_NAME = "agent-skills-builder"
SKILL_VERSION = "v0.10.0"
WORKSPACE_ROOT = Path(__file__).resolve().parents[3]
ARTIFACT_ROOT = WORKSPACE_ROOT / "coreclaw-skills-hub" / ".artifacts" / "generated-skills"
DEFAULT_GROUP_ICON = "🧰"
DEFAULT_ORCHESTRATOR_TOOLS = ["Read", "Grep", "Glob", "TodoWrite"]
DEFAULT_EXECUTION_AGENT_TOOLS = ["Read", "Grep", "Glob", "Bash"]
DEFAULT_SUB_AGENT_TOOLS = ["Read", "Grep"]
HARNESS_PROFILE_ALIASES = {
    "": "standard",
    "default": "standard",
    "standard": "standard",
    "strict": "strict",
    "minimal": "minimal",
}
SUPPORTED_TARGET_FORMAT_ALIASES = {
    "agent-skills": "agent-skills",
    "agentskills": "agent-skills",
    "copilot": "agent-skills",
    "copilot-cli": "agent-skills",
    "github-copilot-cli": "agent-skills",
}
SUITE_PROFILE_ALIASES = {
    "default": "ops",
    "standard": "ops",
    "ops": "ops",
    "operations": "ops",
    "research": "research",
    "researcher": "research",
    "consulting": "consulting",
    "consultant": "consulting",
}


def _slugify(value: str) -> str:
    slug = re.sub(r"[^a-z0-9-]+", "-", value.lower()).strip("-")
    slug = re.sub(r"-+", "-", slug)
    return slug or "generated-skill"


def _target_format(payload: dict) -> tuple[str, str | None]:
    raw = _stringify(
        payload.get("target_format")
        or payload.get("format")
        or payload.get("skill_format")
        or payload.get("output_format")
    ).lower()
    if not raw:
        return "agent-skills", None
    normalized = SUPPORTED_TARGET_FORMAT_ALIASES.get(raw)
    if normalized:
        return normalized, None
    return "agent-skills", f"target_format '{raw}' is no longer supported; generated Agent Skills output instead."


def _agent_skill_name(value: str) -> str:
    return _slugify(value)[:64].strip("-") or "generated-skill"


def _artifact_dir(skill_name: str) -> Path:
    return ARTIFACT_ROOT / _slugify(skill_name)


def _display_name(skill_name: str) -> str:
    return " ".join(part.capitalize() for part in _slugify(skill_name).split("-"))


def _normalize_version(value: str | None) -> str:
    if not value:
        return "v0.1.0"
    normalized = value if value.startswith("v") else f"v{value}"
    if re.match(r"^v\d+\.\d+\.\d+$", normalized):
        return normalized
    return "v0.1.0"


def _stringify(value: object | None) -> str:
    return str(value).strip() if value is not None else ""


def _default_description(payload: dict, title: str) -> str:
    description = (
        payload.get("description")
        or payload.get("true_objective")
        or payload.get("surface_request")
        or payload.get("user_request")
    )
    if description:
        return _stringify(description)
    return f"{title} skill scaffold generated by agent-skills-builder."


def _default_group_description(group_title: str, root_description: str) -> str:
    if root_description:
        return root_description
    return f"Skills for {group_title.lower()} workflows."


def _default_orchestrator_description(group_title: str) -> str:
    return f"Coordinates the {group_title.lower()} workflow across specialized sub-skills with shared quality gates."


def _default_subskill_description(skill_title: str, group_title: str) -> str:
    return f"Executes the {skill_title.lower()} step inside the {group_title.lower()} workflow."


def _workflow_label(group_title: str) -> str:
    label = group_title.lower().strip()
    return label if label.endswith("workflow") else f"{label} workflow"


def _suite_profile(payload: dict) -> str:
    raw = _stringify(
        payload.get("suite_profile")
        or payload.get("profile")
        or payload.get("domain")
        or payload.get("workflow_type")
    ).lower()
    return SUITE_PROFILE_ALIASES.get(raw, "ops")


def _default_subskill_role_specs(group_name: str, group_title: str, profile: str) -> list[dict[str, str]]:
    presets = {
        "ops": [
            {
                "name": f"{group_name}-intake",
                "title": f"{group_title} Intake",
                "description": f"Captures the request scope, constraints, dependencies, and handoff requirements for the {group_title.lower()} workflow.",
            },
            {
                "name": f"{group_name}-execution",
                "title": f"{group_title} Execution",
                "description": f"Performs the core execution step for the {group_title.lower()} workflow and produces the primary working artifacts.",
            },
            {
                "name": f"{group_name}-reporting",
                "title": f"{group_title} Reporting",
                "description": f"Consolidates outputs, verifies quality gates, and prepares final deliverables for the {group_title.lower()} workflow.",
            },
        ],
        "research": [
            {
                "name": f"{group_name}-intake",
                "title": f"{group_title} Intake",
                "description": f"Frames the research objective, scope, data sources, and evaluation criteria for the {group_title.lower()} workflow.",
            },
            {
                "name": f"{group_name}-evidence-synthesis",
                "title": f"{group_title} Evidence Synthesis",
                "description": f"Synthesizes evidence, methods, and intermediate findings for the {group_title.lower()} workflow.",
            },
            {
                "name": f"{group_name}-report-assembly",
                "title": f"{group_title} Report Assembly",
                "description": f"Assembles validated findings, limitations, and conclusions into final research deliverables for the {group_title.lower()} workflow.",
            },
        ],
        "consulting": [
            {
                "name": f"{group_name}-problem-structuring",
                "title": f"{group_title} Problem Structuring",
                "description": f"Defines the decision problem, hypotheses, constraints, and workplan for the {group_title.lower()} workflow.",
            },
            {
                "name": f"{group_name}-analysis",
                "title": f"{group_title} Analysis",
                "description": f"Builds the fact base, analysis outputs, and implications for the {group_title.lower()} workflow.",
            },
            {
                "name": f"{group_name}-executive-storyline",
                "title": f"{group_title} Executive Storyline",
                "description": f"Converts analysis into executive recommendations, storyline structure, and client-ready deliverables for the {group_title.lower()} workflow.",
            },
        ],
    }
    return presets.get(profile, presets["ops"])


def _suite_requested(payload: dict, explicit_files: dict[str, str]) -> bool:
    structure = _stringify(payload.get("structure_type") or payload.get("structure") or payload.get("template_mode")).lower()
    if structure in {"suite", "suite-style", "group"}:
        return True
    if payload.get("suite_style") is True or payload.get("generate_group") is True:
        return True
    if payload.get("subskills") or payload.get("sub_skills") or payload.get("sub_agents"):
        return True
    return any(path == "group.json" or ("/" in path and not path.startswith("source/")) for path in explicit_files)


def _yaml_scalar(value: str) -> str:
    if not value:
        return '""'
    if re.match(r"^[A-Za-z0-9._/-]+$", value):
        return value
    return json.dumps(value, ensure_ascii=False)


def _yaml_list(values: list[str], indent: int = 0) -> list[str]:
    prefix = " " * indent
    return [f"{prefix}- {_yaml_scalar(value)}" for value in values]


def _normalize_tools(value: object, default: list[str]) -> list[str]:
    if isinstance(value, list):
        tools = [_stringify(item) for item in value if _stringify(item)]
        return tools or list(default)
    if isinstance(value, str):
        parsed = [part.strip() for part in re.split(r"[,\n]", value) if part.strip()]
        return parsed or list(default)
    return list(default)


def _role_model_tier(role: str) -> str:
    if role == "orchestrator":
        return "premium"
    if role == "agent":
        return "standard"
    return "fast"


def _harness_profile(payload: dict) -> str:
    raw = _stringify(payload.get("harness_profile") or payload.get("hook_profile") or payload.get("profile_mode")).lower()
    return HARNESS_PROFILE_ALIASES.get(raw, "standard")


def _should_emit_harness_scaffold(payload: dict, is_suite: bool) -> bool:
    requested = payload.get("include_harness_scaffold")
    if requested is not None:
        return bool(requested)
    return is_suite


def _render_hooks_json(profile: str) -> str:
    hooks = {
        "profile": profile,
        "PreToolUse": [
            {
                "matcher": "Bash",
                "hooks": [
                    {
                        "type": "command",
                        "command": "node scripts/hooks/pre-bash-safety.js",
                        "timeout": 10,
                    }
                ],
                "description": "Block risky shell usage and remind the agent to keep changes reviewable.",
            }
        ],
        "PostToolUse": [
            {
                "matcher": "Edit|Write|MultiEdit",
                "hooks": [
                    {
                        "type": "command",
                        "command": "node scripts/hooks/post-edit-quality-gate.js",
                        "async": True,
                        "timeout": 30,
                    }
                ],
                "description": "Run a lightweight quality gate after file edits.",
            }
        ],
        "Stop": [
            {
                "matcher": "*",
                "hooks": [
                    {
                        "type": "command",
                        "command": "node scripts/hooks/stop-cost-tracker.js",
                        "async": True,
                        "timeout": 10,
                    }
                ],
                "description": "Capture session-level metrics and suggested next checks.",
            }
        ],
    }
    if profile == "strict":
        hooks["PreToolUse"].append(
            {
                "matcher": "Write|Edit|MultiEdit",
                "hooks": [
                    {
                        "type": "command",
                        "command": "node scripts/hooks/config-protection.js",
                        "timeout": 10,
                    }
                ],
                "description": "Prevent weakening lint or formatter configuration during agent edits.",
            }
        )
    return json.dumps(hooks, ensure_ascii=False, indent=2) + "\n"


def _render_hook_script(name: str, body: str) -> str:
    return f'''#!/usr/bin/env node
// {name}

{body}
'''


def _render_harness_audit_doc(group_title: str, profile: str) -> str:
    return f'''# Harness Audit

Collection: {group_title}
Profile: {profile}

## Categories

1. Tool Coverage
2. Context Efficiency
3. Quality Gates
4. Memory Persistence
5. Eval Coverage
6. Security Guardrails
7. Cost Efficiency

## Review Checklist

- Confirm hooks/hooks.json matches the intended enforcement profile.
- Confirm agents and sub-agents have explicit tool boundaries.
- Confirm orchestration contracts are file-backed and reviewable.
- Confirm eval, verify, and checkpoint commands exist and match the workflow.
- Confirm quality gates are documented before release.

## Top Actions Template

1. [Category] First measurable improvement
2. [Category] Second measurable improvement
3. [Category] Third measurable improvement
'''


def _render_command_doc(title: str, purpose: str, steps: list[str]) -> str:
    return f'''# {title}

{purpose}

## Steps

{chr(10).join(f'- {step}' for step in steps)}
'''


def _render_harness_scaffold_files(group_name: str, group_title: str, profile: str) -> dict[str, str]:
    return {
        "hooks/hooks.json": _render_hooks_json(profile),
        "scripts/hooks/pre-bash-safety.js": _render_hook_script(
            "pre-bash-safety",
            "const blocked = ['rm -rf', '--no-verify'];\nconst input = process.argv.slice(2).join(' ');\nif (blocked.some((item) => input.includes(item))) {\n  console.error('Blocked risky shell pattern:', input);\n  process.exit(2);\n}\nconsole.log('pre-bash-safety: ok');",
        ),
        "scripts/hooks/post-edit-quality-gate.js": _render_hook_script(
            "post-edit-quality-gate",
            "console.log('post-edit-quality-gate: run lint, tests, or validators here');",
        ),
        "scripts/hooks/stop-cost-tracker.js": _render_hook_script(
            "stop-cost-tracker",
            "console.log('stop-cost-tracker: capture token and cost metrics here');",
        ),
        "scripts/hooks/config-protection.js": _render_hook_script(
            "config-protection",
            "console.log('config-protection: validate config changes before accepting them');",
        ),
        "docs/harness-audit.md": _render_harness_audit_doc(group_title, profile),
        "commands/eval.md": _render_command_doc(
            "eval",
            "Run a lightweight evaluation pass against the generated harness and orchestration contracts.",
            [
                "Review orchestration.json and identify the critical success path.",
                "Score pass criteria for each orchestrator, agent, and sub-agent role.",
                "Record failures before release or promotion.",
            ],
        ),
        "commands/verify.md": _render_command_doc(
            "verify",
            "Verify that hooks, contracts, and generated skill files remain internally consistent.",
            [
                "Check every generated SKILL.md and agent manifest for required sections.",
                "Confirm hooks.json references existing scripts.",
                "Confirm release artifacts and output contracts are aligned.",
            ],
        ),
        "commands/checkpoint.md": _render_command_doc(
            "checkpoint",
            "Capture the current harness state at a logical milestone before moving to the next phase.",
            [
                "Summarize completed work and active assumptions.",
                "List unresolved blockers and next validation step.",
                "Persist the checkpoint summary to a reviewable file.",
            ],
        ),
    }


def _render_agent_manifest(
    name: str,
    description: str,
    role: str,
    tools: list[str],
    handoff_to: list[str],
    responsibilities: list[str],
    quality_gates: list[str],
    output_contract: list[str],
) -> str:
    title = " ".join(part.capitalize() for part in name.split("-"))
    lines = [
        "---",
        f"name: {name}",
        "description: |",
        f"  {description}",
        f"role: {role}",
        f"model: {_role_model_tier(role)}",
        "tools:",
        *(_yaml_list(tools, indent=2)),
    ]
    if handoff_to:
        lines.append("handoff_to:")
        lines.extend(_yaml_list(handoff_to, indent=2))
    lines.append("---")
    body = [
        "",
        f"# {title}",
        "",
        description,
        "",
        "## Responsibilities",
        "",
        *(f"- {item}" for item in responsibilities),
        "",
        "## Output Contract",
        "",
        *(f"- {item}" for item in output_contract),
        "",
        "## Quality Gates",
        "",
        *(f"- {item}" for item in quality_gates),
    ]
    if handoff_to:
        body.extend([
            "",
            "## Handoff Targets",
            "",
            *(f"- {item}" for item in handoff_to),
        ])
    return "\n".join(lines + body)


def _suite_agent_name(payload: dict, group_name: str) -> str:
    return _agent_skill_name(payload.get("agent_name") or f"{group_name}-agent")


def _suite_agent_description(group_title: str) -> str:
    return f"Executes the {group_title.lower()} workflow under orchestrator direction and dispatches specialized sub-agents."


def _sub_agent_manifest_name(subskill_name: str) -> str:
    return _agent_skill_name(f"{subskill_name}-sub-agent")


def _render_orchestration_schema(
    group_name: str,
    group_title: str,
    suite_profile: str,
    orchestrator_name: str,
    orchestrator_contracts: dict[str, list[str]],
    execution_agent_name: str,
    subskills: list[dict[str, str]],
) -> str:
    data = {
        "collection": group_name,
        "title": group_title,
        "suite_profile": suite_profile,
        "orchestration": {
            "orchestrator": {
                "skill": f"{orchestrator_name}/SKILL.md",
                "agent_manifest": f"agents/{orchestrator_name}.md",
                "dispatches": [execution_agent_name],
            },
            "agent": {
                "name": execution_agent_name,
                "agent_manifest": f"agents/{execution_agent_name}.md",
                "dispatches": [_sub_agent_manifest_name(item["name"]) for item in subskills],
            },
            "sub_agents": [
                {
                    "name": _sub_agent_manifest_name(item["name"]),
                    "skill": f"{item['name']}/SKILL.md",
                    "agent_manifest": f"agents/{_sub_agent_manifest_name(item['name'])}.md",
                    "specialty": item["title"],
                }
                for item in subskills
            ],
        },
        "contracts": orchestrator_contracts,
        "harness_recommendations": {
            "quality_gates": [
                "Run validation after each generated file set.",
                "Keep orchestrator handoff contracts explicit and file-backed.",
                "Require final output summary with assumptions, risks, and next steps.",
            ],
            "memory_persistence": [
                "Persist reusable generation decisions in repository memory.",
                "Compact investigation context after architecture confirmation.",
            ],
            "cost_efficiency": [
                "Use fast-tier sub-agents for exploration and scaffolding.",
                "Reserve premium-tier reasoning for orchestration and architecture decisions.",
            ],
        },
    }
    return json.dumps(data, ensure_ascii=False, indent=2) + "\n"


def _render_agent_frontmatter(name: str, description: str, payload: dict) -> str:
    lines = ["---", f"name: {name}", "description: |", f"  {description}"]

    license_value = _stringify(payload.get("license"))
    if license_value:
        lines.append(f"license: {_yaml_scalar(license_value)}")

    compatibility = _stringify(payload.get("compatibility"))
    if compatibility:
        lines.append(f"compatibility: {_yaml_scalar(compatibility)}")

    metadata = payload.get("metadata") or {}
    if isinstance(metadata, dict) and metadata:
        lines.append("metadata:")
        for key, value in metadata.items():
            lines.append(f"  {_slugify(str(key)).replace('-', '_')}: {_yaml_scalar(_stringify(value))}")

    allowed_tools = payload.get("allowed_tools") or payload.get("allowed-tools")
    if isinstance(allowed_tools, list):
        allowed_tools_value = " ".join(_stringify(item) for item in allowed_tools if _stringify(item))
    else:
        allowed_tools_value = _stringify(allowed_tools)
    if allowed_tools_value:
        lines.append(f"allowed-tools: {_yaml_scalar(allowed_tools_value)}")

    lines.append("---")
    return "\n".join(lines)


def _render_agent_body(skill_name: str, title: str, description: str, payload: dict, role_summary: str | None = None) -> str:
    when_to_use = _stringify(payload.get("when_to_use")) or description
    quick_steps = [
        "Read the task request and confirm the expected outcome.",
        "Review any referenced files or scripts in this skill before acting.",
        "Produce the requested artifact and summarize key assumptions.",
    ]
    edge_cases = [
        "If required context is missing, ask for the minimum clarification needed.",
        "If dependencies or tools are unavailable, state the limitation and provide a fallback path.",
    ]
    role_line = f"\n## Role\n\n- {role_summary}\n" if role_summary else ""
    return f'''{_render_agent_frontmatter(skill_name, description, payload)}

# {title}

{description}

## When to Use

- {when_to_use}

{role_line}
## Instructions

1. Parse the request and identify the target deliverable.
2. Gather the minimum required inputs, constraints, and references.
3. Execute the task using this skill's guidance and any packaged resources.
4. Return a concise result with assumptions, risks, and next steps.

## Example Inputs

- A user asks for help related to {title.lower()}.
- The request includes constraints, desired output format, or attached context.

## Example Outputs

- A completed task artifact or actionable recommendation.
- A short summary of what was done and any remaining gaps.

## Quick Start

{chr(10).join(f'- {step}' for step in quick_steps)}

## Edge Cases

{chr(10).join(f'- {item}' for item in edge_cases)}
'''


def _render_agent_collection_readme(collection_name: str, skill_dirs: list[str], agent_manifests: list[str], harness_assets: list[str]) -> str:
    items = "\n".join(f"- `{item}`" for item in skill_dirs)
    manifests = "\n".join(f"- `{item}`" for item in agent_manifests)
    harness = "\n".join(f"- `{item}`" for item in harness_assets)
    return f'''# {collection_name}

Generated skill collection in `agent-skills` format.

## Included Skills

{items}

## Included Agent Manifests

{manifests}

## Orchestration Assets

- `orchestration.json`

## Harness Scaffolds

{harness}

Each listed directory is an individual Agent Skill with its own `SKILL.md`.
'''


def _render_agent_single_files(payload: dict) -> tuple[dict[str, str], dict[str, object]]:
    skill_name = _agent_skill_name(payload.get("skill_name") or payload.get("name") or "generated-skill")
    title = _stringify(payload.get("title")) or _display_name(skill_name)
    description = _default_description(payload, title)
    files = {
        "SKILL.md": _render_agent_body(skill_name, title, description, payload),
    }
    return files, {
        "structure_type": "single",
        "target_format": "agent-skills",
        "skill_name": skill_name,
    }


def _render_agent_suite_files(payload: dict) -> tuple[dict[str, str], dict[str, object]]:
    group_name = _agent_skill_name(payload.get("group_name") or payload.get("skill_name") or payload.get("name") or "generated-collection")
    group_title = _stringify(payload.get("group_title") or payload.get("title")) or _display_name(group_name)
    suite_profile = _suite_profile(payload)
    orchestrator_name = _agent_skill_name(payload.get("orchestrator_name") or f"{group_name}-orchestrator")
    execution_agent_name = _suite_agent_name(payload, group_name)
    orchestrator_description = _stringify(payload.get("orchestrator_description")) or _default_orchestrator_description(group_title)
    execution_agent_description = _stringify(payload.get("agent_description")) or _suite_agent_description(group_title)
    orchestrator_contracts = _orchestrator_profile_contracts(group_title, suite_profile)
    subskills = _normalize_subskills(payload, group_name, group_title)
    harness_profile = _harness_profile(payload)
    harness_scaffold_enabled = _should_emit_harness_scaffold(payload, True)
    orchestrator_tools = _normalize_tools(payload.get("orchestrator_tools"), DEFAULT_ORCHESTRATOR_TOOLS)
    agent_tools = _normalize_tools(payload.get("agent_tools"), DEFAULT_EXECUTION_AGENT_TOOLS)
    sub_agent_tools = _normalize_tools(payload.get("sub_agent_tools") or payload.get("subagent_tools"), DEFAULT_SUB_AGENT_TOOLS)
    agent_manifest_names = [orchestrator_name, execution_agent_name, *[_sub_agent_manifest_name(item["name"]) for item in subskills]]
    harness_assets = []
    harness_files = {}
    if harness_scaffold_enabled:
        harness_files = _render_harness_scaffold_files(group_name, group_title, harness_profile)
        harness_assets = sorted(harness_files.keys())

    files: dict[str, str] = {
        "README.md": _render_agent_collection_readme(
            group_name,
            [orchestrator_name, *[item["name"] for item in subskills]],
            agent_manifest_names,
            harness_assets,
        ),
        "orchestration.json": _render_orchestration_schema(
            group_name,
            group_title,
            suite_profile,
            orchestrator_name,
            orchestrator_contracts,
            execution_agent_name,
            subskills,
        ),
        f"{orchestrator_name}/SKILL.md": _render_agent_body(
            orchestrator_name,
            _display_name(orchestrator_name),
            orchestrator_description,
            {
                **payload,
                "metadata": {
                    **(payload.get("metadata") or {}),
                    "suite_profile": suite_profile,
                    "role": "orchestrator",
                },
            },
            role_summary="Routes work across specialized skills and validates the outputs before final delivery.",
        ) + f'''\n\n## Orchestration Flow\n\n- {'\n- '.join(item['name'] for item in subskills)}\n\n## Input Contract\n\n- {'\n- '.join(orchestrator_contracts['input_contract'])}\n\n## Output Contract\n\n- {'\n- '.join(orchestrator_contracts['output_contract'])}\n\n## Quality Gates\n\n- {'\n- '.join(orchestrator_contracts['quality_gates'])}\n\n## Fallback Policy\n\n- {'\n- '.join(orchestrator_contracts['fallback_policy'])}\n''',
        f"agents/{orchestrator_name}.md": _render_agent_manifest(
            orchestrator_name,
            orchestrator_description,
            "orchestrator",
            orchestrator_tools,
            [execution_agent_name],
            [
                "Interpret the workflow objective and choose the smallest valid execution path.",
                "Dispatch the execution agent with complete contracts, constraints, and quality gates.",
                "Review returned artifacts before final delivery.",
            ],
            orchestrator_contracts["quality_gates"],
            orchestrator_contracts["output_contract"],
        ),
        f"agents/{execution_agent_name}.md": _render_agent_manifest(
            execution_agent_name,
            execution_agent_description,
            "agent",
            agent_tools,
            [_sub_agent_manifest_name(item["name"]) for item in subskills],
            [
                "Translate orchestrator intent into an ordered sub-agent execution plan.",
                "Maintain shared assumptions, constraints, and working state across sub-agents.",
                "Assemble sub-agent outputs into a coherent delivery package.",
            ],
            [
                "Sub-agent handoffs stay aligned with the orchestrator input contract.",
                "Intermediate outputs remain traceable to the producing sub-agent.",
                "Final assembled output is ready for orchestrator review.",
            ],
            [
                "Ordered execution summary",
                "Consolidated artifact inventory",
                "Integrated response draft for orchestrator review",
            ],
        ),
    }
    files.update(harness_files)

    for item in subskills:
        files[f"{item['name']}/SKILL.md"] = _render_agent_body(
            item["name"],
            item["title"],
            item["description"],
            {
                **payload,
                "metadata": {
                    **(payload.get("metadata") or {}),
                    "suite_profile": suite_profile,
                    "role": "specialized-subskill",
                },
            },
            role_summary=f"Handles the {item['title'].lower()} step within the collection.",
        )
        sub_agent_name = _sub_agent_manifest_name(item["name"])
        files[f"agents/{sub_agent_name}.md"] = _render_agent_manifest(
            sub_agent_name,
            f"Specialized sub-agent for the {item['title'].lower()} stage in the {group_title.lower()} workflow.",
            "sub-agent",
            sub_agent_tools,
            [],
            [
                f"Execute the {item['title'].lower()} stage using the provided input contract.",
                "Return structured outputs, assumptions, and unresolved risks.",
                "Stop and surface blockers instead of guessing through missing prerequisites.",
            ],
            [
                "Outputs are parseable and ready for the parent agent to merge.",
                "Assumptions and confidence levels are explicit.",
                "The response includes any blockers or missing context.",
            ],
            [
                f"{item['title']} stage output",
                "Assumptions, confidence, and open issues",
            ],
        )

    return files, {
        "structure_type": "suite",
        "target_format": "agent-skills",
        "collection_name": group_name,
        "suite_profile": suite_profile,
        "orchestrator_name": orchestrator_name,
        "agent_name": execution_agent_name,
        "subskills": [item["name"] for item in subskills],
        "sub_agents": [_sub_agent_manifest_name(item["name"]) for item in subskills],
        "orchestrator_contracts": orchestrator_contracts,
        "harness_files": ["README.md", "orchestration.json", *[f"agents/{name}.md" for name in agent_manifest_names], *harness_assets],
        "harness_profile": harness_profile,
        "harness_scaffold": harness_scaffold_enabled,
    }


def _default_subskill_specs(group_name: str, group_title: str, profile: str) -> list[dict[str, str]]:
    return _default_subskill_role_specs(group_name, group_title, profile)


def _orchestrator_profile_contracts(group_title: str, profile: str) -> dict[str, list[str]]:
    workflow_label = _workflow_label(group_title)
    defaults = {
        "input_contract": [
            f"Workflow objective for {workflow_label}",
            "Shared context, constraints, and quality gates",
            "Expected output format for downstream delivery",
        ],
        "output_contract": [
            "Ordered execution plan across sub-skills",
            "Consolidated artifact summary with assumptions",
            "Final recommendation and next actions",
        ],
        "quality_gates": [
            "Upstream outputs are complete and parseable before moving to the next skill.",
            "Each step records assumptions, constraints, and confidence levels.",
            "The final response includes recommended next actions.",
        ],
        "fallback_policy": [
            "If a sub-skill output is insufficient, request clarification and rerun that step.",
            "If constraints conflict, present at least two viable alternatives.",
        ],
    }
    profiles = {
        "ops": {
            "input_contract": [
                f"Operational objective and service boundaries for the {workflow_label}",
                "Runbook constraints, dependencies, and escalation paths",
                "Required artifact formats for downstream operators",
            ],
            "output_contract": [
                "Sequenced operational handoff across sub-skills",
                "Validated execution artifacts with blockers and mitigations",
                "Actionable rollout or remediation plan",
            ],
            "quality_gates": [
                "Every stage records dependencies, owners, and rollback conditions.",
                "Execution artifacts are complete enough for downstream operational handoff.",
                "The final response includes operational next actions and risk notes.",
            ],
            "fallback_policy": [
                "If an execution dependency is missing, stop the chain and surface the blocking prerequisite.",
                "If a rollback or escalation path is unclear, return a safe fallback plan before continuing.",
            ],
        },
        "research": {
            "input_contract": [
                f"Research objective, hypothesis scope, and evaluation criteria for the {workflow_label}",
                "Data sources, methodological constraints, and evidence standards",
                "Required artifact formats for analysis and final reporting",
            ],
            "output_contract": [
                "Ordered research workflow across intake, synthesis, and reporting",
                "Traceable evidence summary with assumptions and limitations",
                "Final findings, conclusions, and recommended next studies",
            ],
            "quality_gates": [
                "Each stage preserves source traceability, assumptions, and limitations.",
                "Synthesis outputs are methodologically consistent before report assembly begins.",
                "The final response separates evidence, interpretation, and recommendations.",
            ],
            "fallback_policy": [
                "If evidence quality is insufficient, document the gap and narrow the claim scope before continuing.",
                "If methods conflict, present the competing interpretations and required follow-up validation.",
            ],
        },
        "consulting": {
            "input_contract": [
                f"Decision objective, client constraints, and success metrics for the {workflow_label}",
                "Hypotheses, stakeholder context, and available fact base",
                "Expected deliverable format for executive communication",
            ],
            "output_contract": [
                "Structured consulting workplan across problem structuring, analysis, and storyline development",
                "Implication-led synthesis with risks, assumptions, and trade-offs",
                "Executive recommendation set with implementation next steps",
            ],
            "quality_gates": [
                "Problem structuring clearly defines the decision, scope, and hypotheses.",
                "Analysis outputs connect facts to implications without unexplained gaps.",
                "The storyline is executive-ready and ends with decisive recommendations.",
            ],
            "fallback_policy": [
                "If the fact base is weak, state the implication limits and propose the minimum additional analysis needed.",
                "If recommendation paths conflict, present the trade-offs and decision criteria explicitly.",
            ],
        },
    }
    return profiles.get(profile, defaults)


def _normalize_subskills(payload: dict, group_name: str, group_title: str) -> list[dict[str, str]]:
    raw = payload.get("subskills") or payload.get("sub_skills") or payload.get("sub_agents") or []
    profile = _suite_profile(payload)
    normalized: list[dict[str, str]] = []
    for index, item in enumerate(raw, start=1):
        if isinstance(item, str):
            skill_name = _slugify(item)
            title = _display_name(skill_name)
            description = _default_subskill_description(title, group_title)
        elif isinstance(item, dict):
            skill_name = _slugify(_stringify(item.get("name") or item.get("skill_name") or item.get("title") or f"{group_name}-specialist-{index}"))
            title = _stringify(item.get("title")) or _display_name(skill_name)
            description = _stringify(item.get("description")) or _default_subskill_description(title, group_title)
        else:
            continue
        normalized.append({
            "name": skill_name,
            "title": title,
            "description": description,
        })
    return normalized or _default_subskill_specs(group_name, group_title, profile)


def _should_generate_template(payload: dict, explicit_files: dict[str, str]) -> bool:
    if payload.get("generate_template") is not None:
        return bool(payload.get("generate_template"))
    if explicit_files:
        return True
    return any(payload.get(key) for key in ("skill_name", "name", "description", "true_objective", "surface_request", "user_request", "group_name"))


def _build_files(payload: dict) -> tuple[dict[str, str], list[str], dict[str, object]]:
    explicit_files = dict(payload.get("files") or {})
    generated_files: list[str] = []
    target_format, target_format_note = _target_format(payload)
    template_meta = {"structure_type": "single", "target_format": target_format}
    if target_format_note:
        template_meta["note"] = target_format_note
    if not _should_generate_template(payload, explicit_files):
        return explicit_files, generated_files, template_meta

    if _suite_requested(payload, explicit_files):
        defaults, defaults_meta = _render_agent_suite_files(payload)
    else:
        defaults, defaults_meta = _render_agent_single_files(payload)
    template_meta.update(defaults_meta)

    for relative_path, content in defaults.items():
        if relative_path not in explicit_files:
            explicit_files[relative_path] = content
            generated_files.append(relative_path)
    return explicit_files, generated_files, template_meta


def _is_within_workspace(path: Path) -> bool:
    try:
        path.resolve().relative_to(WORKSPACE_ROOT.resolve())
        return True
    except ValueError:
        return False


def _default_output_name(input_data: dict) -> str:
    if _suite_requested(input_data, dict(input_data.get("files") or {})):
        return _slugify(input_data.get("group_name") or input_data.get("skill_name") or input_data.get("name") or "generated-group")
    return _slugify(input_data.get("skill_name") or input_data.get("name") or SKILL_NAME)


def _resolve_output_dir(input_data: dict) -> tuple[Path, str | None]:
    default_dir = _artifact_dir(_default_output_name(input_data))
    requested = input_data.get("output_dir")
    if not requested:
        return default_dir, None

    candidate = Path(requested)
    candidate = candidate if candidate.is_absolute() else (WORKSPACE_ROOT / candidate)
    if _is_within_workspace(candidate):
        return candidate, None

    return default_dir, f"Requested output_dir '{requested}' is outside the workspace; saved to artifact-visible path instead."


def _write_files(output_dir: Path, files: dict[str, str]) -> list[str]:
    written_files: list[str] = []
    for relative_path, content in files.items():
        destination = output_dir / relative_path
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_text(content, encoding="utf-8")
        written_files.append(str(destination.relative_to(WORKSPACE_ROOT)))
    return sorted(written_files)


def _zip_directory(output_dir: Path) -> dict:
    zip_path = output_dir.with_suffix(".zip")
    files_packed = 0
    with ZipFile(zip_path, "w", compression=ZIP_DEFLATED) as archive:
        for file_path in sorted(output_dir.rglob("*")):
            if file_path.is_file():
                archive.write(file_path, arcname=file_path.relative_to(output_dir))
                files_packed += 1
    return {
        "created": True,
        "zip_path": str(zip_path.relative_to(WORKSPACE_ROOT)),
        "files_packed": files_packed,
    }


def run(input_data: dict | None = None) -> dict:
    payload = input_data or {}
    output_dir, fallback_note = _resolve_output_dir(payload)
    output_dir.mkdir(parents=True, exist_ok=True)

    files, generated_files, template_meta = _build_files(payload)
    written_files = _write_files(output_dir, files) if files else []

    zip_bundle = {
        "created": False,
        "zip_path": None,
        "files_packed": 0,
    }
    if payload.get("create_zip"):
        zip_bundle = _zip_directory(output_dir)

    result = {
        "skill": SKILL_NAME,
        "version": SKILL_VERSION,
        "skill_path": SKILL_NAME,
        "status": "artifact-output-ready",
        "capabilities": [
            "agent-skills-compliant-output",
            "agent-skills-only-output",
            "verification-loop",
            "quality-gates",
            "harness-optimized",
            "eval-criteria",
            "model-routing",
            "sub-agent-orchestration",
            "error-recovery",
            "token-optimization",
            "artifact-visible-output",
            "zip-bundling",
            "minimal-template-generation",
            "suite-template-generation",
            "suite-profile-presets",
            "profile-specific-orchestrator-contracts",
            "orchestrator-agent-sub-agent-generation",
            "orchestration-schema-output",
            "agent-manifest-output",
        ],
        "artifact_output": {
            "workspace_root": str(WORKSPACE_ROOT),
            "artifact_root": str(ARTIFACT_ROOT.relative_to(WORKSPACE_ROOT)),
            "output_dir": str(output_dir.relative_to(WORKSPACE_ROOT)),
            "written_files": written_files,
            "generated_template_files": generated_files,
            "template_mode": template_meta.get("structure_type", "single"),
            "target_format": template_meta.get("target_format", "agent-skills"),
        },
        "template_summary": template_meta,
        "zip_bundle": zip_bundle,
        "harness": {
            "verification_loop": "PLAN → EXECUTE → VERIFY → RECOVER → REPORT",
            "quality_gates": [
                "skill-structure-valid",
                "required-entry-files-exist",
                "skill-md-structure-complete",
                "kebab-case-naming",
                "semver-version",
                "character-limits-respected",
                "zip-bundle-generated",
                "true-objective-documented",
                "artifact-visible-output",
                "minimal-template-generated",
                "suite-group-generated",
                "suite-profile-selected",
                "profile-orchestrator-contracts-generated",
                "agent-manifests-generated",
                "orchestration-schema-generated",
            ],
            "model_routing": {
                "fast": "File scaffolding, JSON generation, ZIP bundling",
                "standard": "SKILL.md writing, README generation, validation",
                "premium": "True objective discovery, architecture decisions",
            },
            "token_optimization": "structured-json-specs",
        },
        "input": payload,
    }
    if fallback_note:
        result["artifact_output"]["note"] = fallback_note
    return result


if __name__ == "__main__":
    print(json.dumps(run(), ensure_ascii=False, indent=2))
