#!/usr/bin/env python3
"""Implementation for agent-skills-builder (v0.9.0).

Harness-optimized with 5-phase verification loops, domain-specific eval criteria,
model routing, sub-agent orchestration, and error recovery protocol.
"""

from __future__ import annotations

import json
import re
from pathlib import Path
from zipfile import ZIP_DEFLATED, ZipFile


SKILL_NAME = "agent-skills-builder"
SKILL_VERSION = "v0.9.0"
WORKSPACE_ROOT = Path(__file__).resolve().parents[3]
ARTIFACT_ROOT = WORKSPACE_ROOT / "coreclaw-skills-hub" / ".artifacts" / "generated-skills"
DEFAULT_GROUP_ICON = "🧰"
SUPPORTED_TARGET_FORMAT_ALIASES = {
    "agent-skills": "agent-skills",
    "agentskills": "agent-skills",
    "copilot": "agent-skills",
    "copilot-cli": "agent-skills",
    "github-copilot-cli": "agent-skills",
}
SUITE_PROFILE_ALIASES = {
    "default": "ops",
    "standard": "ops",
    "ops": "ops",
    "operations": "ops",
    "research": "research",
    "researcher": "research",
    "consulting": "consulting",
    "consultant": "consulting",
}


def _slugify(value: str) -> str:
    slug = re.sub(r"[^a-z0-9-]+", "-", value.lower()).strip("-")
    slug = re.sub(r"-+", "-", slug)
    return slug or "generated-skill"


def _target_format(payload: dict) -> tuple[str, str | None]:
    raw = _stringify(
        payload.get("target_format")
        or payload.get("format")
        or payload.get("skill_format")
        or payload.get("output_format")
    ).lower()
    if not raw:
        return "agent-skills", None
    normalized = SUPPORTED_TARGET_FORMAT_ALIASES.get(raw)
    if normalized:
        return normalized, None
    return "agent-skills", f"target_format '{raw}' is no longer supported; generated Agent Skills output instead."


def _agent_skill_name(value: str) -> str:
    return _slugify(value)[:64].strip("-") or "generated-skill"


def _artifact_dir(skill_name: str) -> Path:
    return ARTIFACT_ROOT / _slugify(skill_name)


def _display_name(skill_name: str) -> str:
    return " ".join(part.capitalize() for part in _slugify(skill_name).split("-"))


def _normalize_version(value: str | None) -> str:
    if not value:
        return "v0.1.0"
    normalized = value if value.startswith("v") else f"v{value}"
    if re.match(r"^v\d+\.\d+\.\d+$", normalized):
        return normalized
    return "v0.1.0"


def _stringify(value: object | None) -> str:
    return str(value).strip() if value is not None else ""


def _default_description(payload: dict, title: str) -> str:
    description = (
        payload.get("description")
        or payload.get("true_objective")
        or payload.get("surface_request")
        or payload.get("user_request")
    )
    if description:
        return _stringify(description)
    return f"{title} skill scaffold generated by agent-skills-builder."


def _default_group_description(group_title: str, root_description: str) -> str:
    if root_description:
        return root_description
    return f"Skills for {group_title.lower()} workflows."


def _default_orchestrator_description(group_title: str) -> str:
    return f"Coordinates the {group_title.lower()} workflow across specialized sub-skills with shared quality gates."


def _default_subskill_description(skill_title: str, group_title: str) -> str:
    return f"Executes the {skill_title.lower()} step inside the {group_title.lower()} workflow."


def _workflow_label(group_title: str) -> str:
    label = group_title.lower().strip()
    return label if label.endswith("workflow") else f"{label} workflow"


def _suite_profile(payload: dict) -> str:
    raw = _stringify(
        payload.get("suite_profile")
        or payload.get("profile")
        or payload.get("domain")
        or payload.get("workflow_type")
    ).lower()
    return SUITE_PROFILE_ALIASES.get(raw, "ops")


def _default_subskill_role_specs(group_name: str, group_title: str, profile: str) -> list[dict[str, str]]:
    presets = {
        "ops": [
            {
                "name": f"{group_name}-intake",
                "title": f"{group_title} Intake",
                "description": f"Captures the request scope, constraints, dependencies, and handoff requirements for the {group_title.lower()} workflow.",
            },
            {
                "name": f"{group_name}-execution",
                "title": f"{group_title} Execution",
                "description": f"Performs the core execution step for the {group_title.lower()} workflow and produces the primary working artifacts.",
            },
            {
                "name": f"{group_name}-reporting",
                "title": f"{group_title} Reporting",
                "description": f"Consolidates outputs, verifies quality gates, and prepares final deliverables for the {group_title.lower()} workflow.",
            },
        ],
        "research": [
            {
                "name": f"{group_name}-intake",
                "title": f"{group_title} Intake",
                "description": f"Frames the research objective, scope, data sources, and evaluation criteria for the {group_title.lower()} workflow.",
            },
            {
                "name": f"{group_name}-evidence-synthesis",
                "title": f"{group_title} Evidence Synthesis",
                "description": f"Synthesizes evidence, methods, and intermediate findings for the {group_title.lower()} workflow.",
            },
            {
                "name": f"{group_name}-report-assembly",
                "title": f"{group_title} Report Assembly",
                "description": f"Assembles validated findings, limitations, and conclusions into final research deliverables for the {group_title.lower()} workflow.",
            },
        ],
        "consulting": [
            {
                "name": f"{group_name}-problem-structuring",
                "title": f"{group_title} Problem Structuring",
                "description": f"Defines the decision problem, hypotheses, constraints, and workplan for the {group_title.lower()} workflow.",
            },
            {
                "name": f"{group_name}-analysis",
                "title": f"{group_title} Analysis",
                "description": f"Builds the fact base, analysis outputs, and implications for the {group_title.lower()} workflow.",
            },
            {
                "name": f"{group_name}-executive-storyline",
                "title": f"{group_title} Executive Storyline",
                "description": f"Converts analysis into executive recommendations, storyline structure, and client-ready deliverables for the {group_title.lower()} workflow.",
            },
        ],
    }
    return presets.get(profile, presets["ops"])


def _suite_requested(payload: dict, explicit_files: dict[str, str]) -> bool:
    structure = _stringify(payload.get("structure_type") or payload.get("structure") or payload.get("template_mode")).lower()
    if structure in {"suite", "suite-style", "group"}:
        return True
    if payload.get("suite_style") is True or payload.get("generate_group") is True:
        return True
    if payload.get("subskills") or payload.get("sub_skills") or payload.get("sub_agents"):
        return True
    return any(path == "group.json" or ("/" in path and not path.startswith("source/")) for path in explicit_files)


def _yaml_scalar(value: str) -> str:
    if not value:
        return '""'
    if re.match(r"^[A-Za-z0-9._/-]+$", value):
        return value
    return json.dumps(value, ensure_ascii=False)


def _render_agent_frontmatter(name: str, description: str, payload: dict) -> str:
    lines = ["---", f"name: {name}", "description: |", f"  {description}"]

    license_value = _stringify(payload.get("license"))
    if license_value:
        lines.append(f"license: {_yaml_scalar(license_value)}")

    compatibility = _stringify(payload.get("compatibility"))
    if compatibility:
        lines.append(f"compatibility: {_yaml_scalar(compatibility)}")

    metadata = payload.get("metadata") or {}
    if isinstance(metadata, dict) and metadata:
        lines.append("metadata:")
        for key, value in metadata.items():
            lines.append(f"  {_slugify(str(key)).replace('-', '_')}: {_yaml_scalar(_stringify(value))}")

    allowed_tools = payload.get("allowed_tools") or payload.get("allowed-tools")
    if isinstance(allowed_tools, list):
        allowed_tools_value = " ".join(_stringify(item) for item in allowed_tools if _stringify(item))
    else:
        allowed_tools_value = _stringify(allowed_tools)
    if allowed_tools_value:
        lines.append(f"allowed-tools: {_yaml_scalar(allowed_tools_value)}")

    lines.append("---")
    return "\n".join(lines)


def _render_agent_body(skill_name: str, title: str, description: str, payload: dict, role_summary: str | None = None) -> str:
    when_to_use = _stringify(payload.get("when_to_use")) or description
    quick_steps = [
        "Read the task request and confirm the expected outcome.",
        "Review any referenced files or scripts in this skill before acting.",
        "Produce the requested artifact and summarize key assumptions.",
    ]
    edge_cases = [
        "If required context is missing, ask for the minimum clarification needed.",
        "If dependencies or tools are unavailable, state the limitation and provide a fallback path.",
    ]
    role_line = f"\n## Role\n\n- {role_summary}\n" if role_summary else ""
    return f'''{_render_agent_frontmatter(skill_name, description, payload)}

# {title}

{description}

## When to Use

- {when_to_use}

{role_line}
## Instructions

1. Parse the request and identify the target deliverable.
2. Gather the minimum required inputs, constraints, and references.
3. Execute the task using this skill's guidance and any packaged resources.
4. Return a concise result with assumptions, risks, and next steps.

## Example Inputs

- A user asks for help related to {title.lower()}.
- The request includes constraints, desired output format, or attached context.

## Example Outputs

- A completed task artifact or actionable recommendation.
- A short summary of what was done and any remaining gaps.

## Quick Start

{chr(10).join(f'- {step}' for step in quick_steps)}

## Edge Cases

{chr(10).join(f'- {item}' for item in edge_cases)}
'''


def _render_agent_collection_readme(collection_name: str, skill_dirs: list[str]) -> str:
    items = "\n".join(f"- `{item}`" for item in skill_dirs)
    return f'''# {collection_name}

Generated skill collection in `agent-skills` format.

## Included Skills

{items}

Each listed directory is an individual Agent Skill with its own `SKILL.md`.
'''


def _render_agent_single_files(payload: dict) -> tuple[dict[str, str], dict[str, object]]:
    skill_name = _agent_skill_name(payload.get("skill_name") or payload.get("name") or "generated-skill")
    title = _stringify(payload.get("title")) or _display_name(skill_name)
    description = _default_description(payload, title)
    files = {
        "SKILL.md": _render_agent_body(skill_name, title, description, payload),
    }
    return files, {
        "structure_type": "single",
        "target_format": "agent-skills",
        "skill_name": skill_name,
    }


def _render_agent_suite_files(payload: dict) -> tuple[dict[str, str], dict[str, object]]:
    group_name = _agent_skill_name(payload.get("group_name") or payload.get("skill_name") or payload.get("name") or "generated-collection")
    group_title = _stringify(payload.get("group_title") or payload.get("title")) or _display_name(group_name)
    suite_profile = _suite_profile(payload)
    orchestrator_name = _agent_skill_name(payload.get("orchestrator_name") or f"{group_name}-orchestrator")
    orchestrator_description = _stringify(payload.get("orchestrator_description")) or _default_orchestrator_description(group_title)
    orchestrator_contracts = _orchestrator_profile_contracts(group_title, suite_profile)
    subskills = _normalize_subskills(payload, group_name, group_title)

    files: dict[str, str] = {
        "README.md": _render_agent_collection_readme(group_name, [orchestrator_name, *[item["name"] for item in subskills]]),
        f"{orchestrator_name}/SKILL.md": _render_agent_body(
            orchestrator_name,
            _display_name(orchestrator_name),
            orchestrator_description,
            {
                **payload,
                "metadata": {
                    **(payload.get("metadata") or {}),
                    "suite_profile": suite_profile,
                    "role": "orchestrator",
                },
            },
            role_summary="Routes work across specialized skills and validates the outputs before final delivery.",
        ) + f'''\n\n## Orchestration Flow\n\n- {'\n- '.join(item['name'] for item in subskills)}\n\n## Input Contract\n\n- {'\n- '.join(orchestrator_contracts['input_contract'])}\n\n## Output Contract\n\n- {'\n- '.join(orchestrator_contracts['output_contract'])}\n\n## Quality Gates\n\n- {'\n- '.join(orchestrator_contracts['quality_gates'])}\n\n## Fallback Policy\n\n- {'\n- '.join(orchestrator_contracts['fallback_policy'])}\n''',
    }

    for item in subskills:
        files[f"{item['name']}/SKILL.md"] = _render_agent_body(
            item["name"],
            item["title"],
            item["description"],
            {
                **payload,
                "metadata": {
                    **(payload.get("metadata") or {}),
                    "suite_profile": suite_profile,
                    "role": "specialized-subskill",
                },
            },
            role_summary=f"Handles the {item['title'].lower()} step within the collection.",
        )

    return files, {
        "structure_type": "suite",
        "target_format": "agent-skills",
        "collection_name": group_name,
        "suite_profile": suite_profile,
        "orchestrator_name": orchestrator_name,
        "subskills": [item["name"] for item in subskills],
        "orchestrator_contracts": orchestrator_contracts,
    }


def _default_subskill_specs(group_name: str, group_title: str, profile: str) -> list[dict[str, str]]:
    return _default_subskill_role_specs(group_name, group_title, profile)


def _orchestrator_profile_contracts(group_title: str, profile: str) -> dict[str, list[str]]:
    workflow_label = _workflow_label(group_title)
    defaults = {
        "input_contract": [
            f"Workflow objective for {workflow_label}",
            "Shared context, constraints, and quality gates",
            "Expected output format for downstream delivery",
        ],
        "output_contract": [
            "Ordered execution plan across sub-skills",
            "Consolidated artifact summary with assumptions",
            "Final recommendation and next actions",
        ],
        "quality_gates": [
            "Upstream outputs are complete and parseable before moving to the next skill.",
            "Each step records assumptions, constraints, and confidence levels.",
            "The final response includes recommended next actions.",
        ],
        "fallback_policy": [
            "If a sub-skill output is insufficient, request clarification and rerun that step.",
            "If constraints conflict, present at least two viable alternatives.",
        ],
    }
    profiles = {
        "ops": {
            "input_contract": [
                f"Operational objective and service boundaries for the {workflow_label}",
                "Runbook constraints, dependencies, and escalation paths",
                "Required artifact formats for downstream operators",
            ],
            "output_contract": [
                "Sequenced operational handoff across sub-skills",
                "Validated execution artifacts with blockers and mitigations",
                "Actionable rollout or remediation plan",
            ],
            "quality_gates": [
                "Every stage records dependencies, owners, and rollback conditions.",
                "Execution artifacts are complete enough for downstream operational handoff.",
                "The final response includes operational next actions and risk notes.",
            ],
            "fallback_policy": [
                "If an execution dependency is missing, stop the chain and surface the blocking prerequisite.",
                "If a rollback or escalation path is unclear, return a safe fallback plan before continuing.",
            ],
        },
        "research": {
            "input_contract": [
                f"Research objective, hypothesis scope, and evaluation criteria for the {workflow_label}",
                "Data sources, methodological constraints, and evidence standards",
                "Required artifact formats for analysis and final reporting",
            ],
            "output_contract": [
                "Ordered research workflow across intake, synthesis, and reporting",
                "Traceable evidence summary with assumptions and limitations",
                "Final findings, conclusions, and recommended next studies",
            ],
            "quality_gates": [
                "Each stage preserves source traceability, assumptions, and limitations.",
                "Synthesis outputs are methodologically consistent before report assembly begins.",
                "The final response separates evidence, interpretation, and recommendations.",
            ],
            "fallback_policy": [
                "If evidence quality is insufficient, document the gap and narrow the claim scope before continuing.",
                "If methods conflict, present the competing interpretations and required follow-up validation.",
            ],
        },
        "consulting": {
            "input_contract": [
                f"Decision objective, client constraints, and success metrics for the {workflow_label}",
                "Hypotheses, stakeholder context, and available fact base",
                "Expected deliverable format for executive communication",
            ],
            "output_contract": [
                "Structured consulting workplan across problem structuring, analysis, and storyline development",
                "Implication-led synthesis with risks, assumptions, and trade-offs",
                "Executive recommendation set with implementation next steps",
            ],
            "quality_gates": [
                "Problem structuring clearly defines the decision, scope, and hypotheses.",
                "Analysis outputs connect facts to implications without unexplained gaps.",
                "The storyline is executive-ready and ends with decisive recommendations.",
            ],
            "fallback_policy": [
                "If the fact base is weak, state the implication limits and propose the minimum additional analysis needed.",
                "If recommendation paths conflict, present the trade-offs and decision criteria explicitly.",
            ],
        },
    }
    return profiles.get(profile, defaults)


def _normalize_subskills(payload: dict, group_name: str, group_title: str) -> list[dict[str, str]]:
    raw = payload.get("subskills") or payload.get("sub_skills") or payload.get("sub_agents") or []
    profile = _suite_profile(payload)
    normalized: list[dict[str, str]] = []
    for index, item in enumerate(raw, start=1):
        if isinstance(item, str):
            skill_name = _slugify(item)
            title = _display_name(skill_name)
            description = _default_subskill_description(title, group_title)
        elif isinstance(item, dict):
            skill_name = _slugify(_stringify(item.get("name") or item.get("skill_name") or item.get("title") or f"{group_name}-specialist-{index}"))
            title = _stringify(item.get("title")) or _display_name(skill_name)
            description = _stringify(item.get("description")) or _default_subskill_description(title, group_title)
        else:
            continue
        normalized.append({
            "name": skill_name,
            "title": title,
            "description": description,
        })
    return normalized or _default_subskill_specs(group_name, group_title, profile)


def _should_generate_template(payload: dict, explicit_files: dict[str, str]) -> bool:
    if payload.get("generate_template") is not None:
        return bool(payload.get("generate_template"))
    if explicit_files:
        return True
    return any(payload.get(key) for key in ("skill_name", "name", "description", "true_objective", "surface_request", "user_request", "group_name"))


def _build_files(payload: dict) -> tuple[dict[str, str], list[str], dict[str, object]]:
    explicit_files = dict(payload.get("files") or {})
    generated_files: list[str] = []
    target_format, target_format_note = _target_format(payload)
    template_meta = {"structure_type": "single", "target_format": target_format}
    if target_format_note:
        template_meta["note"] = target_format_note
    if not _should_generate_template(payload, explicit_files):
        return explicit_files, generated_files, template_meta

    if _suite_requested(payload, explicit_files):
        defaults, defaults_meta = _render_agent_suite_files(payload)
    else:
        defaults, defaults_meta = _render_agent_single_files(payload)
    template_meta.update(defaults_meta)

    for relative_path, content in defaults.items():
        if relative_path not in explicit_files:
            explicit_files[relative_path] = content
            generated_files.append(relative_path)
    return explicit_files, generated_files, template_meta


def _is_within_workspace(path: Path) -> bool:
    try:
        path.resolve().relative_to(WORKSPACE_ROOT.resolve())
        return True
    except ValueError:
        return False


def _default_output_name(input_data: dict) -> str:
    if _suite_requested(input_data, dict(input_data.get("files") or {})):
        return _slugify(input_data.get("group_name") or input_data.get("skill_name") or input_data.get("name") or "generated-group")
    return _slugify(input_data.get("skill_name") or input_data.get("name") or SKILL_NAME)


def _resolve_output_dir(input_data: dict) -> tuple[Path, str | None]:
    default_dir = _artifact_dir(_default_output_name(input_data))
    requested = input_data.get("output_dir")
    if not requested:
        return default_dir, None

    candidate = Path(requested)
    candidate = candidate if candidate.is_absolute() else (WORKSPACE_ROOT / candidate)
    if _is_within_workspace(candidate):
        return candidate, None

    return default_dir, f"Requested output_dir '{requested}' is outside the workspace; saved to artifact-visible path instead."


def _write_files(output_dir: Path, files: dict[str, str]) -> list[str]:
    written_files: list[str] = []
    for relative_path, content in files.items():
        destination = output_dir / relative_path
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_text(content, encoding="utf-8")
        written_files.append(str(destination.relative_to(WORKSPACE_ROOT)))
    return sorted(written_files)


def _zip_directory(output_dir: Path) -> dict:
    zip_path = output_dir.with_suffix(".zip")
    files_packed = 0
    with ZipFile(zip_path, "w", compression=ZIP_DEFLATED) as archive:
        for file_path in sorted(output_dir.rglob("*")):
            if file_path.is_file():
                archive.write(file_path, arcname=file_path.relative_to(output_dir))
                files_packed += 1
    return {
        "created": True,
        "zip_path": str(zip_path.relative_to(WORKSPACE_ROOT)),
        "files_packed": files_packed,
    }


def run(input_data: dict | None = None) -> dict:
    payload = input_data or {}
    output_dir, fallback_note = _resolve_output_dir(payload)
    output_dir.mkdir(parents=True, exist_ok=True)

    files, generated_files, template_meta = _build_files(payload)
    written_files = _write_files(output_dir, files) if files else []

    zip_bundle = {
        "created": False,
        "zip_path": None,
        "files_packed": 0,
    }
    if payload.get("create_zip"):
        zip_bundle = _zip_directory(output_dir)

    result = {
        "skill": SKILL_NAME,
        "version": SKILL_VERSION,
        "skill_path": SKILL_NAME,
        "status": "artifact-output-ready",
        "capabilities": [
            "agent-skills-compliant-output",
            "agent-skills-only-output",
            "verification-loop",
            "quality-gates",
            "harness-optimized",
            "eval-criteria",
            "model-routing",
            "sub-agent-orchestration",
            "error-recovery",
            "token-optimization",
            "artifact-visible-output",
            "zip-bundling",
            "minimal-template-generation",
            "suite-template-generation",
            "suite-profile-presets",
            "profile-specific-orchestrator-contracts",
        ],
        "artifact_output": {
            "workspace_root": str(WORKSPACE_ROOT),
            "artifact_root": str(ARTIFACT_ROOT.relative_to(WORKSPACE_ROOT)),
            "output_dir": str(output_dir.relative_to(WORKSPACE_ROOT)),
            "written_files": written_files,
            "generated_template_files": generated_files,
            "template_mode": template_meta.get("structure_type", "single"),
            "target_format": template_meta.get("target_format", "agent-skills"),
        },
        "template_summary": template_meta,
        "zip_bundle": zip_bundle,
        "harness": {
            "verification_loop": "PLAN → EXECUTE → VERIFY → RECOVER → REPORT",
            "quality_gates": [
                "skill-structure-valid",
                "required-entry-files-exist",
                "skill-md-structure-complete",
                "kebab-case-naming",
                "semver-version",
                "character-limits-respected",
                "zip-bundle-generated",
                "true-objective-documented",
                "artifact-visible-output",
                "minimal-template-generated",
                "suite-group-generated",
                "suite-profile-selected",
                "profile-orchestrator-contracts-generated",
            ],
            "model_routing": {
                "fast": "File scaffolding, JSON generation, ZIP bundling",
                "standard": "SKILL.md writing, README generation, validation",
                "premium": "True objective discovery, architecture decisions",
            },
            "token_optimization": "structured-json-specs",
        },
        "input": payload,
    }
    if fallback_note:
        result["artifact_output"]["note"] = fallback_note
    return result


if __name__ == "__main__":
    print(json.dumps(run(), ensure_ascii=False, indent=2))
