#!/usr/bin/env python3
"""Entrypoint for imported skill: agent-skills-builder (v0.8.0).

Harness-optimized with 5-phase verification loops, domain-specific eval criteria,
model routing, sub-agent orchestration, and error recovery protocol.
"""

from __future__ import annotations

import json
import re
from pathlib import Path
from zipfile import ZIP_DEFLATED, ZipFile


SKILL_NAME = "agent-skills-builder"
SKILL_VERSION = "v0.8.0"
WORKSPACE_ROOT = Path(__file__).resolve().parents[3]
ARTIFACT_ROOT = WORKSPACE_ROOT / "coreclaw-skills-hub" / ".artifacts" / "generated-skills"
DEFAULT_GROUP_ICON = "🧰"
SUITE_PROFILE_ALIASES = {
    "default": "ops",
    "standard": "ops",
    "ops": "ops",
    "operations": "ops",
    "research": "research",
    "researcher": "research",
    "consulting": "consulting",
    "consultant": "consulting",
}


def _slugify(value: str) -> str:
    slug = re.sub(r"[^a-z0-9-]+", "-", value.lower()).strip("-")
    return slug or "generated-skill"


def _artifact_dir(skill_name: str) -> Path:
    return ARTIFACT_ROOT / _slugify(skill_name)


def _display_name(skill_name: str) -> str:
    return " ".join(part.capitalize() for part in _slugify(skill_name).split("-"))


def _normalize_version(value: str | None) -> str:
    if not value:
        return "v0.1.0"
    normalized = value if value.startswith("v") else f"v{value}"
    if re.match(r"^v\d+\.\d+\.\d+$", normalized):
        return normalized
    return "v0.1.0"


def _stringify(value: object | None) -> str:
    return str(value).strip() if value is not None else ""


def _default_description(payload: dict, title: str) -> str:
    description = (
        payload.get("description")
        or payload.get("true_objective")
        or payload.get("surface_request")
        or payload.get("user_request")
    )
    if description:
        return _stringify(description)
    return f"{title} skill scaffold generated by agent-skills-builder."


def _default_group_description(group_title: str, root_description: str) -> str:
    if root_description:
        return root_description
    return f"Skills for {group_title.lower()} workflows."


def _default_orchestrator_description(group_title: str) -> str:
    return f"Coordinates the {group_title.lower()} workflow across specialized sub-skills with shared quality gates."


def _default_subskill_description(skill_title: str, group_title: str) -> str:
    return f"Executes the {skill_title.lower()} step inside the {group_title.lower()} workflow."


def _workflow_label(group_title: str) -> str:
    label = group_title.lower().strip()
    return label if label.endswith("workflow") else f"{label} workflow"


def _suite_profile(payload: dict) -> str:
    raw = _stringify(
        payload.get("suite_profile")
        or payload.get("profile")
        or payload.get("domain")
        or payload.get("workflow_type")
    ).lower()
    return SUITE_PROFILE_ALIASES.get(raw, "ops")


def _default_subskill_role_specs(group_name: str, group_title: str, profile: str) -> list[dict[str, str]]:
    presets = {
        "ops": [
            {
                "name": f"{group_name}-intake",
                "title": f"{group_title} Intake",
                "description": f"Captures the request scope, constraints, dependencies, and handoff requirements for the {group_title.lower()} workflow.",
            },
            {
                "name": f"{group_name}-execution",
                "title": f"{group_title} Execution",
                "description": f"Performs the core execution step for the {group_title.lower()} workflow and produces the primary working artifacts.",
            },
            {
                "name": f"{group_name}-reporting",
                "title": f"{group_title} Reporting",
                "description": f"Consolidates outputs, verifies quality gates, and prepares final deliverables for the {group_title.lower()} workflow.",
            },
        ],
        "research": [
            {
                "name": f"{group_name}-intake",
                "title": f"{group_title} Intake",
                "description": f"Frames the research objective, scope, data sources, and evaluation criteria for the {group_title.lower()} workflow.",
            },
            {
                "name": f"{group_name}-evidence-synthesis",
                "title": f"{group_title} Evidence Synthesis",
                "description": f"Synthesizes evidence, methods, and intermediate findings for the {group_title.lower()} workflow.",
            },
            {
                "name": f"{group_name}-report-assembly",
                "title": f"{group_title} Report Assembly",
                "description": f"Assembles validated findings, limitations, and conclusions into final research deliverables for the {group_title.lower()} workflow.",
            },
        ],
        "consulting": [
            {
                "name": f"{group_name}-problem-structuring",
                "title": f"{group_title} Problem Structuring",
                "description": f"Defines the decision problem, hypotheses, constraints, and workplan for the {group_title.lower()} workflow.",
            },
            {
                "name": f"{group_name}-analysis",
                "title": f"{group_title} Analysis",
                "description": f"Builds the fact base, analysis outputs, and implications for the {group_title.lower()} workflow.",
            },
            {
                "name": f"{group_name}-executive-storyline",
                "title": f"{group_title} Executive Storyline",
                "description": f"Converts analysis into executive recommendations, storyline structure, and client-ready deliverables for the {group_title.lower()} workflow.",
            },
        ],
    }
    return presets.get(profile, presets["ops"])


def _suite_requested(payload: dict, explicit_files: dict[str, str]) -> bool:
    structure = _stringify(payload.get("structure_type") or payload.get("structure") or payload.get("template_mode")).lower()
    if structure in {"suite", "suite-style", "group"}:
        return True
    if payload.get("suite_style") is True or payload.get("generate_group") is True:
        return True
    if payload.get("subskills") or payload.get("sub_skills") or payload.get("sub_agents"):
        return True
    return any(path == "group.json" or ("/" in path and not path.startswith("source/")) for path in explicit_files)


def _render_skill_json(skill_name: str, version: str, description: str, entrypoint: str) -> str:
    data = {
        "name": skill_name,
        "version": version,
        "description": description,
        "entrypoint": entrypoint,
    }
    return json.dumps(data, ensure_ascii=False, indent=2) + "\n"


def _render_group_json(group_title: str, description: str, icon: str, count: int) -> str:
    data = {
        "name": group_title,
        "description": description,
        "icon": icon,
        "count": count,
    }
    return json.dumps(data, ensure_ascii=False, indent=2) + "\n"


def _render_main_py(skill_name: str, version: str, description: str, capabilities: list[str] | None = None, status: str = "ready") -> str:
    skill_meta = {
        "name": skill_name,
        "version": version,
        "description": description,
        "capabilities": capabilities or ["artifact-output", "verification-loop"],
    }
    return f'''#!/usr/bin/env python3
"""Entrypoint for generated skill: {skill_name} ({version})."""

from __future__ import annotations

SKILL_META = {repr(skill_meta)}


def run(input_data: dict | None = None) -> dict:
    return {{
        "skill": SKILL_META["name"],
        "version": SKILL_META["version"],
        "description": SKILL_META["description"],
        "status": "{status}",
        "input": input_data or {{}},
    }}


if __name__ == "__main__":
    print(run())
'''


def _render_single_readme(title: str, description: str) -> str:
    return f'''# {title}

{description}

## Features

- Generated by agent-skills-builder
- Includes required CoreClaw skill metadata
- Ready for artifact-visible review and further customization

## Quick Start

```bash
python main.py
```

## Output

- `skill.json`
- `main.py`
- `README.md`
- `SKILL.md`
- `source/SKILL.md`
'''


def _render_suite_root_readme(root_skill_name: str, group_name: str, version: str, orchestrator_name: str, subskills: list[dict[str, str]]) -> str:
    subskill_lines = "\n".join(f"- Includes specialized skill: `{item['name']}`" for item in subskills)
    return f'''# {root_skill_name}

Coordinated skill suite for the `{group_name}` workflow.

- Source path: `{group_name}`
- Original definition: `source/SKILL.md`
- Imported version: `{version}`
- Includes orchestrator: `{orchestrator_name}`
{subskill_lines}
'''


def _render_subskill_readme(title: str, description: str, role_label: str) -> str:
    return f'''# {title}

{description}

## Role

- {role_label}
- Generated by agent-skills-builder
- Ready for workflow-specific customization

## Quick Start

```bash
python main.py
```
'''


def _render_single_skill_md(skill_name: str, title: str, version: str, description: str) -> str:
    return f'''---
name: {skill_name}
description: |
  {description}
---

# {title} {version}

{description}

## When to Use

- When you need a starting point for the {title} workflow
- When you want a CoreClaw-compliant skill scaffold for further editing

## Quick Start

```python
from main import run

result = run({{"task": "demo"}})
print(result)
```

## Verification Loop

```
Phase 1: PLAN
  |-- Confirm purpose and inputs
  |-- Identify required outputs
  +-- Check naming and versioning

Phase 2: EXECUTE
  |-- Prepare skill metadata
  |-- Run the skill entrypoint
  +-- Save outputs as artifacts when needed

Phase 3: VERIFY
  |-- Confirm required files exist
  |-- Validate naming and version format
  +-- Check output structure

Phase 4: REPORT
  |-- Summarize what was generated
  |-- List artifact paths
  +-- Record follow-up customization points
```
'''


def _render_suite_root_skill_md(
    root_skill_name: str,
    group_name: str,
    group_title: str,
    version: str,
    description: str,
    orchestrator_name: str,
    subskills: list[dict[str, str]],
) -> str:
    subskill_lines = "\n".join(f"- Specialized sub-skill: `{item['name']}`" for item in subskills)
    return f'''---
name: {root_skill_name}
description: |
  {group_title} skill suite for coordinated multi-step workflows.
  Includes an orchestrator plus specialized sub-skills designed
  to produce higher-quality outcomes through structured chaining.
---

# {group_title}

This suite is a coordinated skill package under `{group_name}`.

## Package Structure

- Root skill: `{root_skill_name}`
- Orchestrator skill: `{orchestrator_name}`
{subskill_lines}

## Orchestration Principle

The orchestrator routes tasks to specialized sub-skills in sequence,
checks intermediate quality gates, and consolidates outputs into a
final actionable result.

## Common Output Requirements

- Explicit assumptions and constraints
- Traceable reasoning between steps
- Final recommendation with next actions
- Artifacts saved as files, not chat-only output

## Description

{description}

---

## Verification Loop ({version})

```
PLAN   → define scope, inputs, expected outputs
EXECUTE → run analysis / generation pipeline
VERIFY  → check outputs against quality gates
REPORT  → deliver structured artifacts with traceable reasoning
```

### Quality Gates

- [ ] All outputs include explicit assumptions and constraints
- [ ] Traceable reasoning between steps
- [ ] Final recommendation with clear next actions
- [ ] Artifacts saved as files under the suite directory
'''


def _render_orchestrator_skill_md(
    orchestrator_name: str,
    orchestrator_title: str,
    description: str,
    flow: list[str],
    input_contract: list[str],
    output_contract: list[str],
    quality_gates: list[str],
    fallback_policy: list[str],
    version: str,
) -> str:
    flow_text = " -> ".join(flow)
    input_lines = "\n".join(f"- {item}" for item in input_contract)
    output_lines = "\n".join(f"- {item}" for item in output_contract)
    gate_lines = "\n".join(f"- {item}" for item in quality_gates)
    fallback_lines = "\n".join(f"- {item}" for item in fallback_policy)
    return f'''---
name: {orchestrator_name}
description: {description}
---

# {orchestrator_name}

## Overview
{description}

## Orchestration Flow
{flow_text}

## Input Contract
{input_lines}

## Output Contract
{output_lines}

## Quality Gates
{gate_lines}

## Fallback Policy
{fallback_lines}

---

## Verification Loop ({version})

```
PLAN   → define scope, inputs, expected outputs
EXECUTE → run skill logic
VERIFY  → check outputs against quality gates
REPORT  → structured result for downstream skills
```

### Quality Gates

- [ ] Explicit assumptions and constraints documented
- [ ] Clear decisions and rationale
- [ ] Actionable next steps provided
'''


def _render_subskill_skill_md(skill_name: str, title: str, version: str, description: str, group_title: str) -> str:
    return f'''---
name: {skill_name}
description: {description}
---

# {skill_name}

## Overview
{description}

## Role in Suite
- Executes one specialized step within the {group_title.lower()} workflow
- Produces artifacts that the orchestrator can validate and merge

## Input Contract
- Task instructions from the orchestrator or user
- Required context, assumptions, and constraints
- Output format expectations for downstream handoff

## Output Contract
- A workflow-specific artifact or analysis result
- Explicit assumptions, constraints, and confidence notes
- Structured next-step recommendations when applicable

## Quality Gates
- Output matches the requested format and scope
- Assumptions are explicit and minimal
- Downstream consumers can use the result without rework

## Quick Start

```python
from main import run

result = run({{"task": "demo"}})
print(result)
```

## Verification Loop ({version})

```
PLAN   → confirm input scope and expected artifact
EXECUTE → perform the specialized workflow step
VERIFY  → check quality gates and handoff readiness
REPORT  → return structured outputs for the suite
```
'''


def _render_package(
    prefix: str,
    skill_name: str,
    title: str,
    version: str,
    description: str,
    skill_md: str,
    readme: str,
    capabilities: list[str],
    entrypoint: str = "main.py",
) -> dict[str, str]:
    base = f"{prefix}/" if prefix else ""
    return {
        f"{base}skill.json": _render_skill_json(skill_name, version, description, entrypoint),
        f"{base}{entrypoint}": _render_main_py(skill_name, version, description, capabilities=capabilities),
        f"{base}README.md": readme,
        f"{base}SKILL.md": skill_md,
        f"{base}source/SKILL.md": skill_md,
    }


def _default_subskill_specs(group_name: str, group_title: str, profile: str) -> list[dict[str, str]]:
    return _default_subskill_role_specs(group_name, group_title, profile)


def _orchestrator_profile_contracts(group_title: str, profile: str) -> dict[str, list[str]]:
    workflow_label = _workflow_label(group_title)
    defaults = {
        "input_contract": [
            f"Workflow objective for {workflow_label}",
            "Shared context, constraints, and quality gates",
            "Expected output format for downstream delivery",
        ],
        "output_contract": [
            "Ordered execution plan across sub-skills",
            "Consolidated artifact summary with assumptions",
            "Final recommendation and next actions",
        ],
        "quality_gates": [
            "Upstream outputs are complete and parseable before moving to the next skill.",
            "Each step records assumptions, constraints, and confidence levels.",
            "The final response includes recommended next actions.",
        ],
        "fallback_policy": [
            "If a sub-skill output is insufficient, request clarification and rerun that step.",
            "If constraints conflict, present at least two viable alternatives.",
        ],
    }
    profiles = {
        "ops": {
            "input_contract": [
                f"Operational objective and service boundaries for the {workflow_label}",
                "Runbook constraints, dependencies, and escalation paths",
                "Required artifact formats for downstream operators",
            ],
            "output_contract": [
                "Sequenced operational handoff across sub-skills",
                "Validated execution artifacts with blockers and mitigations",
                "Actionable rollout or remediation plan",
            ],
            "quality_gates": [
                "Every stage records dependencies, owners, and rollback conditions.",
                "Execution artifacts are complete enough for downstream operational handoff.",
                "The final response includes operational next actions and risk notes.",
            ],
            "fallback_policy": [
                "If an execution dependency is missing, stop the chain and surface the blocking prerequisite.",
                "If a rollback or escalation path is unclear, return a safe fallback plan before continuing.",
            ],
        },
        "research": {
            "input_contract": [
                f"Research objective, hypothesis scope, and evaluation criteria for the {workflow_label}",
                "Data sources, methodological constraints, and evidence standards",
                "Required artifact formats for analysis and final reporting",
            ],
            "output_contract": [
                "Ordered research workflow across intake, synthesis, and reporting",
                "Traceable evidence summary with assumptions and limitations",
                "Final findings, conclusions, and recommended next studies",
            ],
            "quality_gates": [
                "Each stage preserves source traceability, assumptions, and limitations.",
                "Synthesis outputs are methodologically consistent before report assembly begins.",
                "The final response separates evidence, interpretation, and recommendations.",
            ],
            "fallback_policy": [
                "If evidence quality is insufficient, document the gap and narrow the claim scope before continuing.",
                "If methods conflict, present the competing interpretations and required follow-up validation.",
            ],
        },
        "consulting": {
            "input_contract": [
                f"Decision objective, client constraints, and success metrics for the {workflow_label}",
                "Hypotheses, stakeholder context, and available fact base",
                "Expected deliverable format for executive communication",
            ],
            "output_contract": [
                "Structured consulting workplan across problem structuring, analysis, and storyline development",
                "Implication-led synthesis with risks, assumptions, and trade-offs",
                "Executive recommendation set with implementation next steps",
            ],
            "quality_gates": [
                "Problem structuring clearly defines the decision, scope, and hypotheses.",
                "Analysis outputs connect facts to implications without unexplained gaps.",
                "The storyline is executive-ready and ends with decisive recommendations.",
            ],
            "fallback_policy": [
                "If the fact base is weak, state the implication limits and propose the minimum additional analysis needed.",
                "If recommendation paths conflict, present the trade-offs and decision criteria explicitly.",
            ],
        },
    }
    return profiles.get(profile, defaults)


def _normalize_subskills(payload: dict, group_name: str, group_title: str) -> list[dict[str, str]]:
    raw = payload.get("subskills") or payload.get("sub_skills") or payload.get("sub_agents") or []
    profile = _suite_profile(payload)
    normalized: list[dict[str, str]] = []
    for index, item in enumerate(raw, start=1):
        if isinstance(item, str):
            skill_name = _slugify(item)
            title = _display_name(skill_name)
            description = _default_subskill_description(title, group_title)
        elif isinstance(item, dict):
            skill_name = _slugify(_stringify(item.get("name") or item.get("skill_name") or item.get("title") or f"{group_name}-specialist-{index}"))
            title = _stringify(item.get("title")) or _display_name(skill_name)
            description = _stringify(item.get("description")) or _default_subskill_description(title, group_title)
        else:
            continue
        normalized.append({
            "name": skill_name,
            "title": title,
            "description": description,
        })
    return normalized or _default_subskill_specs(group_name, group_title, profile)


def _render_single_files(payload: dict) -> dict[str, str]:
    skill_name = _slugify(payload.get("skill_name") or payload.get("name") or "generated-skill")
    title = _stringify(payload.get("title")) or _display_name(skill_name)
    version = _normalize_version(payload.get("version"))
    description = _default_description(payload, title)
    entrypoint = _stringify(payload.get("entrypoint")) or "main.py"
    skill_md = _render_single_skill_md(skill_name, title, version, description)
    return {
        "skill.json": _render_skill_json(skill_name, version, description, entrypoint),
        entrypoint: _render_main_py(skill_name, version, description),
        "README.md": _render_single_readme(title, description),
        "SKILL.md": skill_md,
        "source/SKILL.md": skill_md,
    }


def _render_suite_files(payload: dict) -> tuple[dict[str, str], dict[str, object]]:
    group_name = _slugify(payload.get("group_name") or payload.get("skill_name") or payload.get("name") or "generated-group")
    group_title = _stringify(payload.get("group_title") or payload.get("title")) or _display_name(group_name)
    version = _normalize_version(payload.get("version"))
    root_skill_name = _slugify(payload.get("root_skill_name") or f"{group_name}-assistant")
    orchestrator_name = _slugify(payload.get("orchestrator_name") or f"{group_name}-orchestrator")
    root_description = _default_description(payload, group_title)
    group_description = _stringify(payload.get("group_description")) or _default_group_description(group_title, root_description)
    group_icon = _stringify(payload.get("group_icon")) or DEFAULT_GROUP_ICON
    suite_profile = _suite_profile(payload)
    orchestrator_contracts = _orchestrator_profile_contracts(group_title, suite_profile)
    subskills = _normalize_subskills(payload, group_name, group_title)

    files: dict[str, str] = {
        "group.json": _render_group_json(group_title, group_description, group_icon, 2 + len(subskills)),
    }

    root_skill_md = _render_suite_root_skill_md(
        root_skill_name,
        group_name,
        group_title,
        version,
        root_description,
        orchestrator_name,
        subskills,
    )
    files.update(
        _render_package(
            "",
            root_skill_name,
            group_title,
            version,
            root_description,
            root_skill_md,
            _render_suite_root_readme(root_skill_name, group_name, version, orchestrator_name, subskills),
            ["artifact-output", "verification-loop", "suite-root", "orchestration-ready"],
        )
    )

    orchestrator_description = _stringify(payload.get("orchestrator_description")) or _default_orchestrator_description(group_title)
    flow = [item["name"] for item in subskills]
    files.update(
        _render_package(
            orchestrator_name,
            orchestrator_name,
            _display_name(orchestrator_name),
            version,
            orchestrator_description,
            _render_orchestrator_skill_md(
                orchestrator_name,
                _display_name(orchestrator_name),
                orchestrator_description,
                flow,
                orchestrator_contracts["input_contract"],
                orchestrator_contracts["output_contract"],
                orchestrator_contracts["quality_gates"],
                orchestrator_contracts["fallback_policy"],
                version,
            ),
            _render_subskill_readme(_display_name(orchestrator_name), orchestrator_description, "Routes and validates suite execution across sub-skills."),
            ["artifact-output", "verification-loop", "orchestrator", "suite-routing"],
        )
    )

    for item in subskills:
        skill_md = _render_subskill_skill_md(item["name"], item["title"], version, item["description"], group_title)
        files.update(
            _render_package(
                item["name"],
                item["name"],
                item["title"],
                version,
                item["description"],
                skill_md,
                _render_subskill_readme(item["title"], item["description"], f"Handles the {item['title'].lower()} step in the suite."),
                ["artifact-output", "verification-loop", "specialized-subskill"],
            )
        )

    metadata = {
        "structure_type": "suite",
        "suite_profile": suite_profile,
        "group_name": group_name,
        "group_title": group_title,
        "root_skill_name": root_skill_name,
        "orchestrator_name": orchestrator_name,
        "subskills": [item["name"] for item in subskills],
        "orchestrator_contracts": orchestrator_contracts,
    }
    return files, metadata


def _should_generate_template(payload: dict, explicit_files: dict[str, str]) -> bool:
    if payload.get("generate_template") is not None:
        return bool(payload.get("generate_template"))
    if explicit_files:
        return True
    return any(payload.get(key) for key in ("skill_name", "name", "description", "true_objective", "surface_request", "user_request", "group_name"))


def _build_files(payload: dict) -> tuple[dict[str, str], list[str], dict[str, object]]:
    explicit_files = dict(payload.get("files") or {})
    generated_files: list[str] = []
    template_meta = {"structure_type": "single"}
    if not _should_generate_template(payload, explicit_files):
        return explicit_files, generated_files, template_meta

    if _suite_requested(payload, explicit_files):
        defaults, template_meta = _render_suite_files(payload)
    else:
        defaults = _render_single_files(payload)

    for relative_path, content in defaults.items():
        if relative_path not in explicit_files:
            explicit_files[relative_path] = content
            generated_files.append(relative_path)
    return explicit_files, generated_files, template_meta


def _is_within_workspace(path: Path) -> bool:
    try:
        path.resolve().relative_to(WORKSPACE_ROOT.resolve())
        return True
    except ValueError:
        return False


def _default_output_name(input_data: dict) -> str:
    if _suite_requested(input_data, dict(input_data.get("files") or {})):
        return _slugify(input_data.get("group_name") or input_data.get("skill_name") or input_data.get("name") or "generated-group")
    return _slugify(input_data.get("skill_name") or input_data.get("name") or SKILL_NAME)


def _resolve_output_dir(input_data: dict) -> tuple[Path, str | None]:
    default_dir = _artifact_dir(_default_output_name(input_data))
    requested = input_data.get("output_dir")
    if not requested:
        return default_dir, None

    candidate = Path(requested)
    candidate = candidate if candidate.is_absolute() else (WORKSPACE_ROOT / candidate)
    if _is_within_workspace(candidate):
        return candidate, None

    return default_dir, f"Requested output_dir '{requested}' is outside the workspace; saved to artifact-visible path instead."


def _write_files(output_dir: Path, files: dict[str, str]) -> list[str]:
    written_files: list[str] = []
    for relative_path, content in files.items():
        destination = output_dir / relative_path
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_text(content, encoding="utf-8")
        written_files.append(str(destination.relative_to(WORKSPACE_ROOT)))
    return sorted(written_files)


def _zip_directory(output_dir: Path) -> dict:
    zip_path = output_dir.with_suffix(".zip")
    files_packed = 0
    with ZipFile(zip_path, "w", compression=ZIP_DEFLATED) as archive:
        for file_path in sorted(output_dir.rglob("*")):
            if file_path.is_file():
                archive.write(file_path, arcname=file_path.relative_to(output_dir))
                files_packed += 1
    return {
        "created": True,
        "zip_path": str(zip_path.relative_to(WORKSPACE_ROOT)),
        "files_packed": files_packed,
    }


def run(input_data: dict | None = None) -> dict:
    payload = input_data or {}
    output_dir, fallback_note = _resolve_output_dir(payload)
    output_dir.mkdir(parents=True, exist_ok=True)

    files, generated_files, template_meta = _build_files(payload)
    written_files = _write_files(output_dir, files) if files else []

    zip_bundle = {
        "created": False,
        "zip_path": None,
        "files_packed": 0,
    }
    if payload.get("create_zip"):
        zip_bundle = _zip_directory(output_dir)

    result = {
        "skill": SKILL_NAME,
        "version": SKILL_VERSION,
        "skill_path": SKILL_NAME,
        "status": "artifact-output-ready",
        "capabilities": [
            "verification-loop",
            "quality-gates",
            "harness-optimized",
            "eval-criteria",
            "model-routing",
            "sub-agent-orchestration",
            "error-recovery",
            "token-optimization",
            "artifact-visible-output",
            "zip-bundling",
            "minimal-template-generation",
            "suite-template-generation",
            "suite-profile-presets",
            "profile-specific-orchestrator-contracts",
        ],
        "artifact_output": {
            "workspace_root": str(WORKSPACE_ROOT),
            "artifact_root": str(ARTIFACT_ROOT.relative_to(WORKSPACE_ROOT)),
            "output_dir": str(output_dir.relative_to(WORKSPACE_ROOT)),
            "written_files": written_files,
            "generated_template_files": generated_files,
            "template_mode": template_meta.get("structure_type", "single"),
        },
        "template_summary": template_meta,
        "zip_bundle": zip_bundle,
        "harness": {
            "verification_loop": "PLAN → EXECUTE → VERIFY → RECOVER → REPORT",
            "quality_gates": [
                "skill-json-schema-valid",
                "entrypoint-file-exists",
                "skill-md-structure-complete",
                "kebab-case-naming",
                "semver-version",
                "character-limits-respected",
                "zip-bundle-generated",
                "true-objective-documented",
                "artifact-visible-output",
                "minimal-template-generated",
                "suite-group-generated",
                "suite-profile-selected",
                "profile-orchestrator-contracts-generated",
            ],
            "model_routing": {
                "fast": "File scaffolding, JSON generation, ZIP bundling",
                "standard": "SKILL.md writing, README generation, validation",
                "premium": "True objective discovery, architecture decisions",
            },
            "token_optimization": "structured-json-specs",
        },
        "input": payload,
    }
    if fallback_note:
        result["artifact_output"]["note"] = fallback_note
    return result


if __name__ == "__main__":
    print(json.dumps(run(), ensure_ascii=False, indent=2))
